# Spanish translations for PACKAGE package.
# Copyright (C) 2015 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# root <amp_21004@yahoo.es>, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-12-03 13:13+0100\n"
"PO-Revision-Date: 2015-09-29 17:13+0200\n"
"Last-Translator: root <amp_21004@yahoo.es>\n"
"Language-Team: Spanish\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:99
#: ../gecosws_config_assistant/controller/AutoSetupController.py:101
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:99
msgid "The URL field is empty!"
msgstr "El campo URL está vacío"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:116
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:124
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:99
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:122
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:143
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:175
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:76
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:92
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:228
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:243
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:263
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:286
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:295
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:304
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:156
#: ../gecosws_config_assistant/controller/AutoSetupController.py:101
#: ../gecosws_config_assistant/controller/AutoSetupController.py:116
#: ../gecosws_config_assistant/controller/AutoSetupController.py:124
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:99
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:122
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:143
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:175
#: ../gecosws_config_assistant/controller/LocalUserController.py:76
#: ../gecosws_config_assistant/controller/LocalUserController.py:92
#: ../gecosws_config_assistant/controller/LocalUserController.py:101
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:228
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:243
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:263
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:286
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:295
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:304
#: ../gecosws_config_assistant/view/LocalUserElemView.py:156
msgid "Please fill all the mandatory fields."
msgstr "Por favor rellene todos los campos obligatorios"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:108
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:106
#: ../gecosws_config_assistant/controller/AutoSetupController.py:108
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:106
msgid "Malformed URL in URL field!"
msgstr "URL mal formada en el campo URL"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:108
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:106
#: ../gecosws_config_assistant/controller/AutoSetupController.py:108
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:106
msgid "Please double-check it."
msgstr "Por favor revísela."

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:116
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
#: ../gecosws_config_assistant/controller/AutoSetupController.py:116
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
msgid "The Username field is empty!"
msgstr "¡El campo Nombre de usuario está vacío!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:124
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:122
#: ../gecosws_config_assistant/controller/AutoSetupController.py:124
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:122
msgid "The Password field is empty!"
msgstr "¡El campo Contraseña está vacío!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:132
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:130
#: ../gecosws_config_assistant/controller/AutoSetupController.py:132
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:130
msgid "Can't connect to GECOS CC!"
msgstr "¡No puedo conectar con el CC GECOS!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:132
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:130
#: ../gecosws_config_assistant/controller/AutoSetupController.py:132
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:130
msgid "Please double-check all the data and your network setup."
msgstr "Por favor revise todos los datos de su conexión de red"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:154
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/AutoSetupProcessView.py:67
#: ../gecosws_config_assistant/controller/AutoSetupController.py:154
msgid "Please wait"
msgstr "Por favor espere"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:164
#: ../gecosws_config_assistant/controller/AutoSetupController.py:164
msgid "Error getting data"
msgstr "Error obteniendo datos"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:165
#: ../gecosws_config_assistant/controller/AutoSetupController.py:165
msgid "Can't read auto setup configuration data from GECOS Control Center!"
msgstr ""
"¡No se pueden leer los datos de configuración desde el Centro de Control "
"GECOS!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:170
#: ../gecosws_config_assistant/controller/AutoSetupController.py:170
msgid "Success getting data from GECOS server"
msgstr "Datos desde el CC GECOS obtenidos con éxito"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:143
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:143
msgid "The GECOS workstation name field is empty!"
msgstr "¡El campo nombre de la estación de trabajo GECOS está vacío!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:162
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:162
msgid "The GECOS workstation name already exist!"
msgstr "¡El nombre de la estación de trabajo ya existe en GECOS!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:162
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:162
msgid "Please choose a different name."
msgstr "Por favor, elija un nombre diferente."

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:175
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:175
msgid "You must select an OU!"
msgstr "¡Debe seleccionar una OU!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:218
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/Template.py:132
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:218
#: ../gecosws_config_assistant/util/Template.py:132
msgid "Can not find user to be used as owner: "
msgstr "No se encuentra el usuario para ser usado como propietario: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:225
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/Template.py:139
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:225
#: ../gecosws_config_assistant/util/Template.py:139
msgid "Can not find group to be used as owner: "
msgstr "No se encuentra el grupo para ser usado como propietario: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:290
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:85
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:290
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:85
msgid "Link to Chef"
msgstr "Vincular a Chef"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:291
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:291
msgid "Register in GECOS CC"
msgstr "Registrar en el CC GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:297
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:318
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:325
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:362
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:443
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:469
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:490
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:497
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:504
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:541
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:665
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:676
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:297
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:318
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:325
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:362
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:443
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:469
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:490
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:497
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:504
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:541
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:665
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:676
msgid "IN PROCESS"
msgstr "EN PROCESO"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:301
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:307
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:313
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:320
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:354
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:399
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:411
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:433
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:452
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:461
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:492
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:499
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:533
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:548
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:571
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:608
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:617
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:626
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:636
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:645
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:654
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:668
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:134
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:139
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:144
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:153
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:163
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:168
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:96
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:106
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:115
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:124
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:129
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:301
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:307
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:313
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:320
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:354
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:399
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:411
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:433
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:452
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:461
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:492
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:499
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:533
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:548
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:571
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:608
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:617
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:626
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:636
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:645
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:654
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:668
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:134
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:139
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:144
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:153
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:163
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:168
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:96
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:101
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:106
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:115
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:124
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:129
msgid "ERROR"
msgstr "ERROR"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:317
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:324
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:361
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:442
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:468
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:474
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:496
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:503
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:540
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:664
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:675
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:682
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:317
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:324
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:361
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:442
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:468
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:474
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:496
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:503
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:540
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:664
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:675
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:682
msgid "DONE"
msgstr "HECHO"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:346
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:525
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:346
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:525
msgid "CANCELED"
msgstr "CANCELADO"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:356
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:535
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:356
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:535
msgid "There was an error while saving validation certificate"
msgstr ""
"Ha ocurrido un error mientras se almacenaba el certificado de validación"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:401
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:573
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:401
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:573
msgid "Can't create/modify /etc/chef/client.rb file"
msgstr "No se puede crear/modificar el fichero /etc/chef/client.rb"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:413
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:413
msgid "Can't link to chef server"
msgstr "No se puede enlazar al servidor Chef"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:435
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:435
msgid "Can't create/modify /etc/chef.control file"
msgstr "No se puede crear/modificar el fichero /etc/chef.control"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:454
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:454
msgid "Can't register the computer in GECOS CC"
msgstr "No se ha podido registrar el ordenador en el CC GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:463
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:463
msgid "Can't save /etc/gcc.control file"
msgstr "No se puede guardar el fichero /etc/gcc.control"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:484
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:484
msgid "Unlink from Chef"
msgstr "Desvincular de Chef"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:485
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:485
msgid "Unregister from GECOS CC"
msgstr "Desvincular de GECOS CC"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:550
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:550
msgid "Can't unregister the computer from GECOS CC"
msgstr "No se ha podido desvincular el ordenador del CC GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:610
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:610
msgid "Can't create/modify /etc/chef/knife.rb file"
msgstr "No se puede crear/modificar el fichero /etc/chef/knife.rb"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:619
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:619
msgid "Can't remove /etc/chef.control file"
msgstr "No se puede borrar el fichero /etc/chef.control"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:628
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:628
msgid "Can't remove /etc/chef/client.pem file"
msgstr "No se puede borrar el fichero /etc/chef/client.pem"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:638
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:655
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:638
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:655
msgid "Can't delete Chef node"
msgstr "No se puede borrar el nodo de Chef"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:647
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:647
msgid "Can't remove /usr/bin/chef-client-wrapper file"
msgstr "No se puede eliminar el fichero /usr/bin/chef-client-wrapper"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:670
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:670
msgid "Can't remove /etc/gcc.control file"
msgstr "No se puede eliminar el fichero /etc/gcc.control"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:700
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:700
msgid "Can't get OUs from GECOS Control Center"
msgstr "No se pueden obtener las OUs desde el CC GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:76
#: ../gecosws_config_assistant/controller/LocalUserController.py:76
msgid "The login field is empty!"
msgstr "¡El campo login está vacío!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:83
#: ../gecosws_config_assistant/controller/LocalUserController.py:83
msgid "The login field contains not allowed characters!"
msgstr "¡El campo login contiene caracteres no permitidos!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:92
#: ../gecosws_config_assistant/controller/LocalUserController.py:92
msgid "The name field is empty!"
msgstr "¡El campo nombre está vacío!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:101
#: ../gecosws_config_assistant/controller/LocalUserController.py:101
msgid "The password field is empty!"
msgstr "¡El campo contraseña está vacío!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:109
#: ../gecosws_config_assistant/controller/LocalUserController.py:109
msgid "The password field contains not allowed characters."
msgstr "¡El campo contraseña contiene caracteres no permitidos!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:157
#: ../gecosws_config_assistant/controller/LocalUserController.py:157
msgid "Do you really want to delete this user? "
msgstr "¿Realmente quiere borrar este usuario?"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:179
#: ../gecosws_config_assistant/controller/MainMenuController.py:179
msgid "The system has a network connection configured"
msgstr "El sistema está conectado a una red"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:181
#: ../gecosws_config_assistant/controller/MainMenuController.py:181
msgid "The system has NO network connection"
msgstr "El sistema NO está conectado a una red"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:184
#: ../gecosws_config_assistant/controller/MainMenuController.py:184
msgid "The system has loaded setup data values from GECOS server"
msgstr ""
"El sistema a obtenido los parámetros básicos de configuración de un servidor "
"GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:186
#: ../gecosws_config_assistant/controller/MainMenuController.py:186
msgid "The system may load setup data values from GECOS server"
msgstr ""
"El sistema debe obtener parámetros de configuración de un servidor GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:189
#: ../gecosws_config_assistant/controller/MainMenuController.py:189
msgid "The system is synchronized with a NTP server"
msgstr "El sistema dispone de sincronización con un servidor NTP"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:191
#: ../gecosws_config_assistant/controller/MainMenuController.py:191
msgid "The system is NOT synchronized with a NTP server"
msgstr "El sistema NO dispone de sincronización con un servidor NTP"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:194
#: ../gecosws_config_assistant/controller/MainMenuController.py:194
msgid "The system is linked to a GECOS server"
msgstr "El sistema está vinculado a un servidor GECOS "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:196
#: ../gecosws_config_assistant/controller/MainMenuController.py:196
msgid "The system is NOT linked to a GECOS server"
msgstr "El sistema NO está vinculado a un servidor GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:203
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:91
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dto/LDAPAuthMethod.py:43
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:145
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:187
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:381
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:296
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:314
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:334
#: ../gecosws_config_assistant/controller/MainMenuController.py:203
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:91
#: ../gecosws_config_assistant/dto/LDAPAuthMethod.py:43
#: ../gecosws_config_assistant/tests/dto/LDAPAuthMethodTest.py:40
#: ../gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../gecosws_config_assistant/view/UserAuthDialog.py:145
#: ../gecosws_config_assistant/view/UserAuthDialog.py:187
#: ../gecosws_config_assistant/view/UserAuthDialog.py:381
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:296
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:314
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:334
msgid "LDAP"
msgstr "LDAP"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:205
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:93
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dto/ADAuthMethod.py:44
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:147
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:189
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:393
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:298
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:311
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:345
#: ../gecosws_config_assistant/controller/MainMenuController.py:205
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:93
#: ../gecosws_config_assistant/dto/ADAuthMethod.py:44
#: ../gecosws_config_assistant/tests/dto/ADAuthMethodTest.py:40
#: ../gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../gecosws_config_assistant/view/UserAuthDialog.py:147
#: ../gecosws_config_assistant/view/UserAuthDialog.py:189
#: ../gecosws_config_assistant/view/UserAuthDialog.py:393
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:298
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:311
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:345
msgid "Active Directory"
msgstr "Active Directory"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:207
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:89
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dto/LocalUsersAuthMethod.py:43
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:143
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:185
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:99
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:317
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:323
#: ../gecosws_config_assistant/controller/MainMenuController.py:207
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:89
#: ../gecosws_config_assistant/dto/LocalUsersAuthMethod.py:43
#: ../gecosws_config_assistant/tests/dto/LocalUsersAuthMethodTest.py:39
#: ../gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../gecosws_config_assistant/view/UserAuthDialog.py:143
#: ../gecosws_config_assistant/view/UserAuthDialog.py:185
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:99
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:317
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:323
msgid "Internal"
msgstr "Interno"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:275
#: ../gecosws_config_assistant/controller/MainMenuController.py:275
msgid "Are you sure you want to update the GECOS Config Assistant?"
msgstr ""
"¿Está seguro de que desea actualizar el Asistente de Configuración GECOS?"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:278
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:286
#: ../gecosws_config_assistant/controller/MainMenuController.py:278
#: ../gecosws_config_assistant/controller/MainMenuController.py:286
msgid "An error occurred during the upgrade"
msgstr "Ha ocurrido un error durante la actualización"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:282
#: ../gecosws_config_assistant/controller/MainMenuController.py:282
msgid "CGA is already at the newest version!"
msgstr "¡ACG ya está en la última versión!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:284
#: ../gecosws_config_assistant/controller/MainMenuController.py:284
msgid "GECOS Config Assistant has been udpated. Please restart GCA"
msgstr ""
"El asistente de configuración GECOS ha sido actualizado. Por favor reinicie "
"el ACG"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/NTPServerController.py:70
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/NTPServerController.py:74
#: ../gecosws_config_assistant/controller/NTPServerController.py:70
#: ../gecosws_config_assistant/controller/NTPServerController.py:74
msgid "Error saving NTP server data."
msgstr "Error guardando los datos del servidor NTP"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/NTPServerController.py:70
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/NTPServerController.py:74
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:364
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
#: ../gecosws_config_assistant/controller/NTPServerController.py:70
#: ../gecosws_config_assistant/controller/NTPServerController.py:74
#: ../gecosws_config_assistant/view/UserAuthDialog.py:364
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
msgid "See log for more details."
msgstr "Vea el log para más detalles"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:163
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:163
msgid ""
"The user authentication data has changed.\n"
"Do you want to setup the user authentication method using this new data?"
msgstr ""
"Los datos de autenticación de usuarios han cambiado..\n"
"¿Quiere configurar el método de autenticación de usuarios utilizando estos "
"datos?"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:228
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:228
msgid "The URI field is empty!"
msgstr "El campo URI está vacío"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:235
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:235
msgid "Malformed LDAP URI!"
msgstr "URI de LDAP mal formada"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:235
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:235
msgid "Please check that the URI starts with 'ldap://' or 'ldaps://'."
msgstr "Por favor compruebe que la URI comienza con 'ldap://' o 'ldaps://'"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:243
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:243
msgid "The users base DN field is empty!"
msgstr "El campo base DN de usuarios está vacío"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:250
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:250
msgid "Can't connect to LDAP server!"
msgstr "No se puede conectar con el servidor LDAP"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:250
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:312
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:250
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:312
msgid "Please check all the fields and your network connection."
msgstr "Por favor compruebe todos los campos y su conexión a internet"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:263
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:263
msgid "The Domain field is empty!"
msgstr "El campo Dominio está vacío"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:277
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:277
msgid "Can't resolv the Active Directory Domain name!"
msgstr "¡No se puede resolver el nombre de dominio de Active Directory!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:278
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:278
msgid "Please check the Domain field and your DNS configuration."
msgstr "Por favor revise el campo Dominio y su configuración DNS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:286
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:286
msgid "The Workgroup field is empty!"
msgstr "¡El campo Grupo de trabajo está vacío!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:294
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:294
msgid "The AD administrator user field is empty!"
msgstr "¡El campo Administrador AD está vacío!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:303
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:303
msgid "The AD administrator password field is empty!"
msgstr "¡El campo Contraseña del administrador AD está vacío!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:311
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:311
msgid "Can't connect to Active Directory server!"
msgstr "¡No se puede conectar con el servidor de Active Directory!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/GecosAccessDataDAO.py:178
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/WorkstationDataDAO.py:183
#: ../gecosws_config_assistant/dao/GecosAccessDataDAO.py:178
#: ../gecosws_config_assistant/dao/WorkstationDataDAO.py:183
msgid "Error removing file:"
msgstr "Error borrando fichero:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/LocalUserDAO.py:119
#: ../gecosws_config_assistant/dao/LocalUserDAO.py:119
msgid "Error creating user: "
msgstr "Error al crear usuario:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/LocalUserDAO.py:131
#: ../gecosws_config_assistant/dao/LocalUserDAO.py:131
msgid "Error modifying user name: "
msgstr "Error al modificar el nombre de usuario:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/LocalUserDAO.py:145
#: ../gecosws_config_assistant/dao/LocalUserDAO.py:145
msgid "Error modifying user password: "
msgstr "Error al modificar la clave del usuario: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/LocalUserDAO.py:169
#: ../gecosws_config_assistant/dao/LocalUserDAO.py:169
msgid "Error deleting user: "
msgstr "Error al borrar el usuario: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/LocalUserDAO.py:179
#: ../gecosws_config_assistant/dao/LocalUserDAO.py:179
msgid "Error deleting user home: "
msgstr "Error al borrar el 'home' del usuario: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/NTPServerDAO.py:68
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:79
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:131
#: ../gecosws_config_assistant/dao/NTPServerDAO.py:68
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:79
#: ../gecosws_config_assistant/util/PackageManager.py:131
msgid "Package installation failed:"
msgstr "La instalación del paquete falló: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/NTPServerDAO.py:95
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:523
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/WorkstationDataDAO.py:81
#: ../gecosws_config_assistant/dao/NTPServerDAO.py:95
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:523
#: ../gecosws_config_assistant/dao/WorkstationDataDAO.py:81
msgid "Error reading file:"
msgstr "Error leyendo fichero: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/NTPServerDAO.py:99
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/NTPServerDAO.py:135
#: ../gecosws_config_assistant/dao/NTPServerDAO.py:99
#: ../gecosws_config_assistant/dao/NTPServerDAO.py:135
msgid "NTPServerDAO used without a proper initialization!"
msgstr "¡NTPServerDAO usando sin una correcta inicialización!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:175
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:201
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:249
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:360
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:387
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:413
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:448
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:484
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:175
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:201
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:249
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:360
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:387
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:413
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:448
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:484
msgid "Error running command: "
msgstr "Error ejecutando el comando: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:498
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:540
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:566
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:498
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:540
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:566
msgid "UserAuthenticationMethodDAO used without a proper initialization!"
msgstr "¡UserAuthenticationMethodDAO usado sin una correcta inicialización!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/WorkstationDataDAO.py:133
#: ../gecosws_config_assistant/dao/WorkstationDataDAO.py:133
msgid "Error writing file:"
msgstr "Error escribiendo fichero:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/JSONUtil.py:55
#: ../gecosws_config_assistant/util/JSONUtil.py:55
msgid "Error reading file: "
msgstr "Error leyendo fichero: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:59
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:99
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:137
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:161
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:192
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:231
#: ../gecosws_config_assistant/util/PackageManager.py:59
#: ../gecosws_config_assistant/util/PackageManager.py:99
#: ../gecosws_config_assistant/util/PackageManager.py:137
#: ../gecosws_config_assistant/util/PackageManager.py:161
#: ../gecosws_config_assistant/util/PackageManager.py:192
#: ../gecosws_config_assistant/util/PackageManager.py:231
msgid "No apt library available"
msgstr "La librería 'apt' no está disponible"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:79
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:120
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:183
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:214
#: ../gecosws_config_assistant/util/PackageManager.py:79
#: ../gecosws_config_assistant/util/PackageManager.py:120
#: ../gecosws_config_assistant/util/PackageManager.py:183
#: ../gecosws_config_assistant/util/PackageManager.py:214
msgid "Package not found:"
msgstr "Paquete no encontrado:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:81
#: ../gecosws_config_assistant/util/PackageManager.py:81
msgid "Package not installed:"
msgstr "Paquete no instalado:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:83
#: ../gecosws_config_assistant/util/PackageManager.py:83
msgid "Package not upgradable:"
msgstr "Paquete no actualizable:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:93
#: ../gecosws_config_assistant/util/PackageManager.py:93
msgid "Package upgrade failed:"
msgstr "Error al actualizar paquete:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:104
#: ../gecosws_config_assistant/util/PackageManager.py:104
msgid "Package upgrade failed!"
msgstr "¡Falló la actualización del paquete!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:122
#: ../gecosws_config_assistant/util/PackageManager.py:122
msgid "Package already installed:"
msgstr "El paquete ya está instalado:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:142
#: ../gecosws_config_assistant/util/PackageManager.py:142
msgid "Package installation failed!"
msgstr "¡Falló la instalación del paquete!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:155
#: ../gecosws_config_assistant/util/PackageManager.py:155
msgid "Package update failed!"
msgstr "¡Falló la actualización del paquete!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:166
#: ../gecosws_config_assistant/util/PackageManager.py:166
msgid "Package cache update failed!"
msgstr "¡Falló la actualización de la caché de paquetes!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:185
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:216
#: ../gecosws_config_assistant/util/PackageManager.py:185
#: ../gecosws_config_assistant/util/PackageManager.py:216
msgid "Package is not installed:"
msgstr "El paquete no está instalado:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:225
#: ../gecosws_config_assistant/util/PackageManager.py:225
msgid "Package removal failed:"
msgstr "Falló la eliminación del paquete:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:236
#: ../gecosws_config_assistant/util/PackageManager.py:236
msgid "Package removal failed!"
msgstr "¡Falló la eliminación de paquete!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/Template.py:150
#: ../gecosws_config_assistant/util/Template.py:150
msgid "Error saving template:"
msgstr "Error al guardar la plantilla:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:66
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:66
msgid "Active Directory credentials needed"
msgstr "Se necesitan las credenciales de Active Directory"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:79
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:79
msgid "To setup or remove the Active Directory authentication method you"
msgstr ""
"Para configurar o desconfigurar el método de autenticación por Active "
"Directory"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:82
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:82
msgid "have to specify an AD administrator user and password:"
msgstr "deberá especificar un usuario administrador de AD y su contraseña:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:87
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:137
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:244
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:140
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:87
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:137
#: ../gecosws_config_assistant/view/UserAuthDialog.py:244
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:140
msgid "Domain:"
msgstr "Dominio:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:94
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:138
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:245
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:147
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:94
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:138
#: ../gecosws_config_assistant/view/UserAuthDialog.py:245
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:147
msgid "Workgroup:"
msgstr "Grupo de trabajo:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:132
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:246
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:154
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:101
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:132
#: ../gecosws_config_assistant/view/UserAuthDialog.py:246
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:154
msgid "User:"
msgstr "Usuario:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:111
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:142
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:98
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:247
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:163
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:111
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:142
#: ../gecosws_config_assistant/view/LocalUserElemView.py:98
#: ../gecosws_config_assistant/view/UserAuthDialog.py:247
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:163
msgid "Password:"
msgstr "Contraseña:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:122
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:91
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:116
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:122
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:91
#: ../gecosws_config_assistant/view/LocalUserElemView.py:116
msgid "Cancel"
msgstr "Cancelar"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:127
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/AutoSetupProcessView.py:72
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:96
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:190
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:109
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:121
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:128
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:83
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:114
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:127
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:96
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:190
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:109
#: ../gecosws_config_assistant/view/LocalUserElemView.py:121
#: ../gecosws_config_assistant/view/LocalUserListView.py:128
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:83
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:114
msgid "Accept"
msgstr "Aceptar"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:164
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:164
msgid "Active Directory connection error"
msgstr "Error de conexión con Active Directory"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:165
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:165
msgid ""
"Can't connect to Active Directory.\n"
"Please double-check all the fields"
msgstr ""
"No se puede conectar a Active Directory.\n"
"Por favor revise todos los campos"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/AutoSetupProcessView.py:51
msgid "Auto setup process"
msgstr "Proceso de la autoconfiguración"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/AutoSetupProcessView.py:64
msgid "Loading setup data from GECOS Server"
msgstr "Obteniendo datos desde el CC GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:66
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:66
msgid "Url Chef Certificate Required"
msgstr "Se necesita la URL del certificado de Chef"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:79
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:79
msgid ""
"You need to enter url with certificate file\n"
" in protocol://domain/resource format"
msgstr ""
"Debe introducir la URL que apunte a su certificado\n"
" en formato protocolo://dominio/recurso"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:83
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:83
msgid "Certificate URL:"
msgstr "URL del certificado:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:121
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:121
msgid "URL connection error"
msgstr "Error de conexión con la URL"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:122
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:122
msgid "Can't get certificate file from this URL"
msgstr "No se puede obtener el fichero de certificado de esta URL"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:76
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:76
msgid "Connect with GECOS Control Center"
msgstr "Conectar con el Centro de Control GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:92
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:92
msgid "Workstation name"
msgstr "Nombre de la estación de trabajo"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:97
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:97
msgid "Workstation name must be unique. Spaces and symbols may be used."
msgstr ""
"El nombre de la estación debe ser único. Se pueden usar espacios y símbolos"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:101
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:101
msgid "This description apperars in the GECOS control center reports."
msgstr "Esta descripción aparece en los informes del Centro de Control GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:105
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:105
msgid "Workstation name:"
msgstr "Nombre de estación:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:118
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:118
msgid "GECOS Control Center Connection parameters"
msgstr "Parámetros de conexión con el Centro de Control GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:122
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:122
msgid "GECOS Control Center URL:"
msgstr "URL del Centro de Control GECOS:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:155
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:155
msgid "Select OU to connect to GECOS Control Center"
msgstr "Seleccione una OU para conectar con el Centro de Control GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:159
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:159
msgid "Search filter:"
msgstr "Filtro de búsqueda:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:167
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:167
msgid "Search"
msgstr "Buscar"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:172
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:172
msgid "Select OU:"
msgstr "Seleccionar OU:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:185
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:228
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosDialog.py:161
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:185
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:228
#: ../gecosws_config_assistant/view/ConnectWithGecosDialog.py:161
msgid "Connect to GECOS CC"
msgstr "Conectar con el CC GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:209
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosDialog.py:145
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:209
#: ../gecosws_config_assistant/view/ConnectWithGecosDialog.py:145
msgid "Disconnect from GECOS CC"
msgstr "Desconectar del CC GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:51
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:51
msgid "GECOS CC connection process"
msgstr "Proceso de conexión con el CC GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:64
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:64
msgid "Check GECOS credentials"
msgstr "Revise las credenciales de GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:67
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:74
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:81
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:88
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:95
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:102
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:67
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:74
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:81
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:88
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:95
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:102
msgid "PENDING"
msgstr "PENDIENTE"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:71
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:71
msgid "Check workstation data"
msgstr "Revise los datos de la estación de trabajo"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:78
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:78
msgid "Get chef certificate"
msgstr "Obtención del certificado de Chef"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:92
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:92
msgid "Register in GECOS"
msgstr "Registrar en GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:99
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:99
msgid "Clean setup data"
msgstr "Limpiar los datos de configuración"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:65
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:141
#: ../gecosws_config_assistant/view/LocalUserElemView.py:65
#: ../gecosws_config_assistant/view/LocalUserElemView.py:141
msgid "Add local user"
msgstr "Añadir un usuario local"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:79
#: ../gecosws_config_assistant/view/LocalUserElemView.py:79
msgid "Name:"
msgstr "Nombre:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:88
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:121
#: ../gecosws_config_assistant/view/LocalUserElemView.py:88
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:121
msgid "Login:"
msgstr "Login:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:107
#: ../gecosws_config_assistant/view/LocalUserElemView.py:107
msgid "Confirm:"
msgstr "Confirmación:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:133
#: ../gecosws_config_assistant/view/LocalUserElemView.py:133
msgid "Modifiy local user"
msgstr "Modificar un usuario local"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:155
#: ../gecosws_config_assistant/view/LocalUserElemView.py:155
msgid "The password confirmation field is empty!"
msgstr "¡El campo Confirmación de contraseña está vacío!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:163
#: ../gecosws_config_assistant/view/LocalUserElemView.py:163
msgid "The password confirmation is different from password"
msgstr "La confirmación de la contraseña es diferente de la contraseña"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:62
#: ../gecosws_config_assistant/view/LocalUserListView.py:62
msgid "Manage local users"
msgstr "Gestionar usuarios locales"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:75
#: ../gecosws_config_assistant/view/LocalUserListView.py:75
msgid "You can create, update or delete local users in this workstation."
msgstr ""
"Puede crear, modificar o borrar usuarios locales a esta estación de trabajo"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:78
#: ../gecosws_config_assistant/view/LocalUserListView.py:78
msgid ""
"It isn't necessary to create here the users that are authenticated by "
"external services (LDAP, AD, ...)"
msgstr ""
"No es necesario crear aquí los usuarios que se autentican mediante servicios "
"externos (LDAP, AD, ...)"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:84
#: ../gecosws_config_assistant/view/LocalUserListView.py:84
msgid "Please check default OEM users and change their passwords when needed:"
msgstr ""
"Por favor, revise los usuarios OEM por defecto y cambie sus contraseñas "
"cuando sea necesario:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:92
#: ../gecosws_config_assistant/view/LocalUserListView.py:92
msgid "Login"
msgstr "Login"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:93
#: ../gecosws_config_assistant/view/LocalUserListView.py:93
msgid "Name"
msgstr "Nombre"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:112
#: ../gecosws_config_assistant/view/LocalUserListView.py:112
msgid "New"
msgstr "Nuevo"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:117
#: ../gecosws_config_assistant/view/LocalUserListView.py:117
msgid "Update"
msgstr "Modificar"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:122
#: ../gecosws_config_assistant/view/LocalUserListView.py:122
msgid "Delete"
msgstr "Borrar"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:51
msgid "GECOS config assistant"
msgstr "Asistente de configuración GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:63
msgid "Check setup requirements"
msgstr "Comprobar requisitos de configuración"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:67
msgid "Connect / disconnect to GECOS Control Center"
msgstr "Vincular / desvincular del Centro de Control GECOS"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:71
msgid "Setup user authentication method"
msgstr "Establecer método de autenticación de usuarios"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:75
msgid "Software manager"
msgstr "Gestor de software"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:79
msgid "Local user manager"
msgstr "Gestión de usuarios locales"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:83
msgid "Update this assistant"
msgstr "Actualizar este asistente"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:88
msgid "View status"
msgstr "Ver estado"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:92
msgid "Close"
msgstr "Cerrar"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:106
msgid "Quit"
msgstr "Salir"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:106
msgid "Do you want to quit?"
msgstr "¿Realmente desea salir?"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/NTPDialog.py:75
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/NTPServerElemView.py:109
#: ../gecosws_config_assistant/view/NTPServerElemView.py:109
msgid ""
"Can't connect with NTP server.\n"
"Please double-check the NTP server address"
msgstr ""
"No se puede conectar con el servidor NTP.\n"
"Por favor revise la dirección del servidor NTP"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/NTPDialog.py:78
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/NTPServerElemView.py:112
#: ../gecosws_config_assistant/view/NTPServerElemView.py:112
msgid "NTP server connection successful"
msgstr "La conexión con el servidor NTP se realizó correctamente"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:65
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:65
msgid "System status"
msgstr "Estado del sistema"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:96
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:98
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:96
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:98
msgid "Assistant version: "
msgstr "Versión del asistente: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:98
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:98
msgid "UNKNOWN VERSION"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:103
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:103
msgid "Workstation name: "
msgstr "Nombre de la estación de trabajo: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:108
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:108
msgid "Time server: "
msgstr "Servidor de tiempo: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:111
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:111
msgid "Network interfaces: "
msgstr "Interfaces de red: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:117
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:117
msgid "GECOS Control Center connection data: "
msgstr "Datos de conexión con el Centro de Control GECOS: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:120
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:120
msgid "Server URL:"
msgstr "URL del servidor: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:124
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:124
msgid "Local users: "
msgstr "Usuarios locales: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:131
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:131
msgid "User authentication method: "
msgstr "Método de autenticación de usuarios: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:134
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:134
msgid "Method:"
msgstr "Método: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:141
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:141
msgid "Server URI:"
msgstr "URI del servidor: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:142
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:213
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:219
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:142
#: ../gecosws_config_assistant/view/UserAuthDialog.py:213
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:219
msgid "Users base DN:"
msgstr "DN base de usuarios: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:143
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:143
msgid "Groups base DN:"
msgstr "DN base de grupos: "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:148
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:148
msgid "No status data!"
msgstr "¡No hay información de estado!"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:209
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:207
#: ../gecosws_config_assistant/view/UserAuthDialog.py:209
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:207
msgid "Please fill the data to setup the LDAP authentication method."
msgstr ""
"Por favor rellene los datos para configurar el método de autenticación por "
"LDAP"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:212
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:212
#: ../gecosws_config_assistant/view/UserAuthDialog.py:212
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:212
msgid "LDAP server URI:"
msgstr "URI del servidor LDAP:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:214
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:226
#: ../gecosws_config_assistant/view/UserAuthDialog.py:214
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:226
msgid "Groups base DN (optional):"
msgstr "DN base de grupos (opcional):"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:215
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:233
#: ../gecosws_config_assistant/view/UserAuthDialog.py:215
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:233
msgid "Bind user DN (optional):"
msgstr "DN de usuaro para enlazar (opcional):"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:216
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:241
#: ../gecosws_config_assistant/view/UserAuthDialog.py:216
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:241
msgid "Bind user password (optional):"
msgstr "Contraseña de usuario para enlazar (opcional):"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:241
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:136
#: ../gecosws_config_assistant/view/UserAuthDialog.py:241
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:136
msgid ""
"Please fill the data to setup the Active Directory authentication method."
msgstr ""
"Por favor rellene los datos para configurar la autenticación mediante Active "
"Directory."

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:272
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:287
#: ../gecosws_config_assistant/view/UserAuthDialog.py:272
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:287
msgid ""
"There is no necessary data to setup the local users authentication method."
msgstr ""
"No se necesitan datos para configurar el método de autenticación mediante "
"usuarios locales."

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:364
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
#: ../gecosws_config_assistant/view/UserAuthDialog.py:364
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
msgid "An error happened while saving the users authentication method!"
msgstr ""
"¡Ha ocurrido un error al guardar el método de autenticación de usuarios "

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:72
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:72
msgid "User authentication method"
msgstr "Método de autenticación de usuarios"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:85
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:85
msgid "The users of this workstation may authenticate by using"
msgstr "Los usuarios de esta estación de trabajo pueden autenticarse usando"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:88
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:88
msgid "an external system like LDAP or Microsoft Active Directory."
msgstr "un sistema externo como LDAP o Microsoft Active Directory."

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:91
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:91
msgid "Also, they can be authenticated by using local users of this O.S."
msgstr "Además, pueden autenticarse usando usuarios locales a este S.O."

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:95
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:95
msgid "Authentication type:"
msgstr "Tipo de autenticación:"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:109
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:109
msgid "Setup"
msgstr "Configurar"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:125
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:125
msgid "Active Directory authentication"
msgstr "Autenticación por Active Directory"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:196
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:196
msgid "LDAP authentication"
msgstr "Autenticación LDAP"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:276
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:276
msgid "Local users authentication"
msgstr "Autenticación mediante usuarios locales"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:377
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:377
msgid "Error saving authentication method"
msgstr "Error al guardar el método de autenticación de usuarios"

#~ msgid "Auto setup error"
#~ msgstr "Error en la configuración automática"

#~ msgid "NTP server URI value isn't in auto setup data!"
#~ msgstr "La URI del servidor NTP no está en los datos de autoconfiguración"

#~ msgid "Can't synchronize with NTP server!"
#~ msgstr "No se puede sincronizar con el servidor NTP"

#~ msgid "Error saving NTP server data!"
#~ msgstr "¡Error guardando los datos del servidor NTP!"

#~ msgid "LDAP authentication method needs data!"
#~ msgstr "¡La autenticación por LDAP necesita datos!"

#~ msgid "LDAP authentication method needs LDAP server URI!"
#~ msgstr "¡La autenticación mediante LDAP necesita la URI del servidor!"

#~ msgid "LDAP authentication method needs LDAP users base DN!"
#~ msgstr "¡La autenticación mediante LDAP necesita el DN base de usuarios!"

#~ msgid "Can't synchronize with LDAP server!"
#~ msgstr "¡No se puede conectar con el servidor LDAP!"

#~ msgid "Can't save LDAP server information!"
#~ msgstr "¡No se puede guardar la información del servidor LDAP!"

#~ msgid "AD authentication method needs data!"
#~ msgstr "¡La autenticación mediante AD necesita datos!"

#~ msgid "AD authentication method needs 'specific_conf' parameter!"
#~ msgstr "¡La autenticación por LDAP necesita el parámetro 'specific_conf'!"

#~ msgid "AD authentication method needs 'ad_properties' parameter!"
#~ msgstr "¡La autenticación por AD necesita el parámetro 'ad_properties'!"

#~ msgid "AD authentication method needs krb5.conf file!"
#~ msgstr "¡La autenticación por AD necesita el fichero krb5.conf!"

#~ msgid "AD authentication method needs sssd.conf file!"
#~ msgstr "¡La autenticación por AD necesita el fichero sssd.conf!"

#~ msgid "AD authentication method needs smb.conf file!"
#~ msgstr "¡La autenticación por AD necesita el fichero smb.conf!"

#~ msgid "AD authentication method needs pam.conf file!"
#~ msgstr "¡La autenticación por AD necesita el fichero pam.conf!"

#~ msgid "Error saving sssd.conf file!"
#~ msgstr "¡Error guardando el fichero sssd.conf!"

#~ msgid "Error saving smb.conf file!"
#~ msgstr "¡Error guardando el fichero smb.conf!"

#~ msgid "Error saving krb5.conf file!"
#~ msgstr "¡Error guardando el fichero krb5.conf!"

#~ msgid "Error saving pam.conf file!"
#~ msgstr "¡Error guardando el fichero pam.conf!"

#~ msgid "Error executing net ads join"
#~ msgstr "Error ejecutando net ads join"

#~ msgid "Error restarting sssd service"
#~ msgstr "Error reiniciando el servicio sssd"

#~ msgid "Error saving my_mkhomedir file"
#~ msgstr "Error guardando el fichero my_mkhomedir"

#~ msgid "Error executing pam-auth-update"
#~ msgstr "Error ejecutando  pam-auth-update"

#~ msgid "Error saving /etc/gca-sssd.control file"
#~ msgstr "Error guardando el fichero /etc/gca-sssd.control"

#~ msgid "AD authentication method needs FQDN!"
#~ msgstr "¡La autenticación por AD necesita el FQDN!"

#~ msgid "AD authentication method needs workgroup!"
#~ msgstr "¡La autenticación por AD necesita el grupo de trabajo!"

#~ msgid ""
#~ "Can't resolv FQDN!\n"
#~ "Please check your DNS configuration."
#~ msgstr ""
#~ "¡No se puede resolver el FQDN!\n"
#~ "Por favor revise su configuración DNS."

#~ msgid "Can't save AD server information!"
#~ msgstr "¡No se puede guardar la información del servidor AD!"

#~ msgid "Authentication method values aren't in auto setup data!"
#~ msgstr ""
#~ "¡No hay valores en la información de autoconfiguración para la "
#~ "autenticación!"

#~ msgid "Error saving validation certificate"
#~ msgstr "Error almacenando el certificado de validación"

#~ msgid "Error linking to Chef"
#~ msgstr "Error vinculando a Chef"

#~ msgid "Error unlinking from Chef"
#~ msgstr "Error desvinculando de Chef"

#~ msgid "Error registering from GECOS CC"
#~ msgstr "Error registrando en CC GECOS"

#~ msgid "Error Registering from GECOS CC"
#~ msgstr "Error registrando en CC GECOS"

#~ msgid "Error unregistering from GECOS CC"
#~ msgstr "Error desvinculando de GECOS CC"

#~ msgid "Error in user data"
#~ msgstr "Error en los datos del usuario"

#~ msgid "Are you sure?"
#~ msgstr "¿Está seguro?"

#~ msgid "Update GECOS Config Assistant"
#~ msgstr "Actualizar el Asistente de Configuración GECOS"

#~ msgid "Update Error"
#~ msgstr "Error al actualizar"

#~ msgid "Error"
#~ msgstr "Error"

#~ msgid "OK"
#~ msgstr "OK"

#~ msgid "Data changed"
#~ msgstr "Datos cambiados"

#~ msgid "Auto setup"
#~ msgstr "Auto configuración"

#~ msgid "Some of the setup parameters can be filled automatically"
#~ msgstr ""
#~ "Algunos parámetros de la configuración se pueden rellenar automáticamente"

#~ msgid "if you have a setup file in your GECOS server."
#~ msgstr "si dispone de un fichero de configuración en su servidor GECOS"

#~ msgid "Auto setup data load:"
#~ msgstr "Datos de configuración cargados:"

#~ msgid "NTP server setup:"
#~ msgstr "Configuración del servidor NTP:"

#~ msgid "User authentication method setup:"
#~ msgstr "Configuración del método de autenticación de usuarios:"

#~ msgid "Network setup"
#~ msgstr "Configuración de red"

#~ msgid "the users, link with the GECOS server and install software"
#~ msgstr "los usuarios, enlazar con el servidor GECOS e instalar software"

#~ msgid "Available network connections are:"
#~ msgstr "Las conexiones de red disponibles son:"

#~ msgid "Interface"
#~ msgstr "Interfaz"

#~ msgid "IP"
#~ msgstr "IP"

#~ msgid "Setup network interface"
#~ msgstr "Configurar conexión de red"

#~ msgid "Time synchronization"
#~ msgstr "Sincronización de hora"

#~ msgid "A precise time is mandatory to coordinate some services"
#~ msgstr "Una hora precisa es necesaria para coordinar algunos servicios"

#~ msgid "Please set your NTP server address:"
#~ msgstr "Por favor establezca la dirección de su servidor NTP:"

#~ msgid "NTP server:"
#~ msgstr "Servidor NTP:"

#~ msgid "Test"
#~ msgstr "Probar"

#~ msgid "Can't synchronize time"
#~ msgstr "No se puede sincronizar la hora"

#~ msgid "Success"
#~ msgstr "Éxito"

#~ msgid "Check basic setup requirements"
#~ msgstr "Comprobación de los requisitos básicos de configuración"
