# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-12-03 13:53+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:107
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:99
#: ../gecosws_config_assistant/controller/AutoSetupController.py:107
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:99
msgid "The URL field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:107
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:122
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:130
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:99
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:122
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:143
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:175
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:76
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:92
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:228
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:243
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:263
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:286
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:295
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:304
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:156
#: ../gecosws_config_assistant/controller/AutoSetupController.py:107
#: ../gecosws_config_assistant/controller/AutoSetupController.py:122
#: ../gecosws_config_assistant/controller/AutoSetupController.py:130
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:99
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:122
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:143
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:175
#: ../gecosws_config_assistant/controller/LocalUserController.py:76
#: ../gecosws_config_assistant/controller/LocalUserController.py:92
#: ../gecosws_config_assistant/controller/LocalUserController.py:101
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:228
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:243
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:263
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:286
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:295
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:304
#: ../gecosws_config_assistant/view/LocalUserElemView.py:156
msgid "Please fill all the mandatory fields."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:114
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:106
#: ../gecosws_config_assistant/controller/AutoSetupController.py:114
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:106
msgid "Malformed URL in URL field!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:114
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:106
#: ../gecosws_config_assistant/controller/AutoSetupController.py:114
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:106
msgid "Please double-check it."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:122
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
#: ../gecosws_config_assistant/controller/AutoSetupController.py:122
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
msgid "The Username field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:130
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:122
#: ../gecosws_config_assistant/controller/AutoSetupController.py:130
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:122
msgid "The Password field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:138
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:130
#: ../gecosws_config_assistant/controller/AutoSetupController.py:138
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:130
msgid "Can't connect to GECOS CC!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:138
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:130
#: ../gecosws_config_assistant/controller/AutoSetupController.py:138
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:130
msgid "Please double-check all the data and your network setup."
msgstr ""

#. Show process view
#. Get auto setup JSON
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:160
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/AutoSetupProcessView.py:67
#: ../gecosws_config_assistant/controller/AutoSetupController.py:160
msgid "Please wait"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:170
#: ../gecosws_config_assistant/controller/AutoSetupController.py:170
msgid "Error getting data"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:171
#: ../gecosws_config_assistant/controller/AutoSetupController.py:171
msgid "Can't read auto setup configuration data from GECOS Control Center!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/AutoSetupController.py:176
#: ../gecosws_config_assistant/controller/AutoSetupController.py:176
msgid "Success getting data from GECOS server"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:143
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:143
msgid "The GECOS workstation name field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:162
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:162
msgid "The GECOS workstation name already exist!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:162
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:162
msgid "Please choose a different name."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:175
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:175
msgid "You must select an OU!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:218
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/Template.py:132
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:218
#: ../gecosws_config_assistant/util/Template.py:132
msgid "Can not find user to be used as owner: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:225
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/Template.py:139
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:225
#: ../gecosws_config_assistant/util/Template.py:139
msgid "Can not find group to be used as owner: "
msgstr ""

#. Linking/unlinking to Chef server
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:290
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:85
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:290
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:85
msgid "Link to Chef"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:291
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:291
msgid "Register in GECOS CC"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:297
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:318
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:325
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:362
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:443
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:469
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:490
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:497
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:504
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:541
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:665
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:676
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:297
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:318
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:325
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:362
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:443
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:469
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:490
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:497
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:504
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:541
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:665
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:676
msgid "IN PROCESS"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:301
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:307
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:313
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:320
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:354
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:399
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:411
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:433
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:452
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:461
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:492
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:499
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:533
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:548
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:571
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:608
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:617
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:626
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:636
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:645
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:654
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:668
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:134
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:139
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:144
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:153
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:163
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:168
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:93
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:98
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:103
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:112
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:121
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProgressView.py:126
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:301
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:307
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:313
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:320
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:354
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:399
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:411
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:433
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:452
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:461
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:492
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:499
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:533
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:548
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:571
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:608
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:617
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:626
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:636
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:645
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:654
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:668
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:134
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:139
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:144
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:153
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:163
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:168
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:93
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:98
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:103
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:112
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:121
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:126
msgid "ERROR"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:317
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:324
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:361
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:442
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:468
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:474
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:496
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:503
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:540
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:664
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:675
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:682
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:317
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:324
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:361
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:442
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:468
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:474
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:496
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:503
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:540
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:664
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:675
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:682
msgid "DONE"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:346
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:525
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:346
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:525
msgid "CANCELED"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:356
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:535
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:356
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:535
msgid "There was an error while saving validation certificate"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:401
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:573
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:401
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:573
msgid "Can't create/modify /etc/chef/client.rb file"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:413
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:413
msgid "Can't link to chef server"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:435
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:435
msgid "Can't create/modify /etc/chef.control file"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:454
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:454
msgid "Can't register the computer in GECOS CC"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:463
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:463
msgid "Can't save /etc/gcc.control file"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:484
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:484
msgid "Unlink from Chef"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:485
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:485
msgid "Unregister from GECOS CC"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:550
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:550
msgid "Can't unregister the computer from GECOS CC"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:610
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:610
msgid "Can't create/modify /etc/chef/knife.rb file"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:619
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:619
msgid "Can't remove /etc/chef.control file"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:628
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:628
msgid "Can't remove /etc/chef/client.pem file"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:638
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:655
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:638
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:655
msgid "Can't delete Chef node"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:647
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:647
msgid "Can't remove /usr/bin/chef-client-wrapper file"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:670
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:670
msgid "Can't remove /etc/gcc.control file"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/ConnectWithGecosCCController.py:700
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:700
msgid "Can't get OUs from GECOS Control Center"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:76
#: ../gecosws_config_assistant/controller/LocalUserController.py:76
msgid "The login field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:83
#: ../gecosws_config_assistant/controller/LocalUserController.py:83
msgid "The login field contains not allowed characters!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:92
#: ../gecosws_config_assistant/controller/LocalUserController.py:92
msgid "The name field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:101
#: ../gecosws_config_assistant/controller/LocalUserController.py:101
msgid "The password field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:109
#: ../gecosws_config_assistant/controller/LocalUserController.py:109
msgid "The password field contains not allowed characters."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/LocalUserController.py:157
#: ../gecosws_config_assistant/controller/LocalUserController.py:157
msgid "Do you really want to delete this user? "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:179
#: ../gecosws_config_assistant/controller/MainMenuController.py:179
msgid "The system has a network connection configured"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:181
#: ../gecosws_config_assistant/controller/MainMenuController.py:181
msgid "The system has NO network connection"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:184
#: ../gecosws_config_assistant/controller/MainMenuController.py:184
msgid "The system has loaded setup data values from GECOS server"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:186
#: ../gecosws_config_assistant/controller/MainMenuController.py:186
msgid "The system may load setup data values from GECOS server"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:189
#: ../gecosws_config_assistant/controller/MainMenuController.py:189
msgid "The system is synchronized with a NTP server"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:191
#: ../gecosws_config_assistant/controller/MainMenuController.py:191
msgid "The system is NOT synchronized with a NTP server"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:194
#: ../gecosws_config_assistant/controller/MainMenuController.py:194
msgid "The system is linked to a GECOS server"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:196
#: ../gecosws_config_assistant/controller/MainMenuController.py:196
msgid "The system is NOT linked to a GECOS server"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:203
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:91
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dto/LDAPAuthMethod.py:43
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:145
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:187
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:381
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:296
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:314
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:334
#: ../gecosws_config_assistant/controller/MainMenuController.py:203
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:91
#: ../gecosws_config_assistant/dto/LDAPAuthMethod.py:43
#: ../gecosws_config_assistant/tests/dto/LDAPAuthMethodTest.py:40
#: ../gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../gecosws_config_assistant/view/UserAuthDialog.py:145
#: ../gecosws_config_assistant/view/UserAuthDialog.py:187
#: ../gecosws_config_assistant/view/UserAuthDialog.py:381
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:296
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:314
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:334
msgid "LDAP"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:205
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:93
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dto/ADAuthMethod.py:44
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:147
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:189
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:393
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:298
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:311
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:345
#: ../gecosws_config_assistant/controller/MainMenuController.py:205
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:93
#: ../gecosws_config_assistant/dto/ADAuthMethod.py:44
#: ../gecosws_config_assistant/tests/dto/ADAuthMethodTest.py:40
#: ../gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../gecosws_config_assistant/view/UserAuthDialog.py:147
#: ../gecosws_config_assistant/view/UserAuthDialog.py:189
#: ../gecosws_config_assistant/view/UserAuthDialog.py:393
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:298
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:311
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:345
msgid "Active Directory"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:207
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:89
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dto/LocalUsersAuthMethod.py:43
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:143
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:185
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:99
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:317
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:323
#: ../gecosws_config_assistant/controller/MainMenuController.py:207
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:89
#: ../gecosws_config_assistant/dto/LocalUsersAuthMethod.py:43
#: ../gecosws_config_assistant/tests/dto/LocalUsersAuthMethodTest.py:39
#: ../gecosws_config_assistant/view/UserAuthDialog.py:64
#: ../gecosws_config_assistant/view/UserAuthDialog.py:143
#: ../gecosws_config_assistant/view/UserAuthDialog.py:185
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:99
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:317
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:323
msgid "Internal"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:275
#: ../gecosws_config_assistant/controller/MainMenuController.py:275
msgid "Are you sure you want to update the GECOS Config Assistant?"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:278
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:286
#: ../gecosws_config_assistant/controller/MainMenuController.py:278
#: ../gecosws_config_assistant/controller/MainMenuController.py:286
msgid "An error occurred during the upgrade"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:282
#: ../gecosws_config_assistant/controller/MainMenuController.py:282
msgid "CGA is already at the newest version!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/MainMenuController.py:284
#: ../gecosws_config_assistant/controller/MainMenuController.py:284
msgid "GECOS Config Assistant has been udpated. Please restart GCA"
msgstr ""

#. Show error message
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/NTPServerController.py:70
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/NTPServerController.py:74
#: ../gecosws_config_assistant/controller/NTPServerController.py:70
#: ../gecosws_config_assistant/controller/NTPServerController.py:74
msgid "Error saving NTP server data."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/NTPServerController.py:70
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/NTPServerController.py:74
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:364
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
#: ../gecosws_config_assistant/controller/NTPServerController.py:70
#: ../gecosws_config_assistant/controller/NTPServerController.py:74
#: ../gecosws_config_assistant/view/UserAuthDialog.py:364
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
msgid "See log for more details."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:163
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:163
msgid ""
"The user authentication data has changed.\n"
"Do you want to setup the user authentication method using this new data?"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:228
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:228
msgid "The URI field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:235
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:235
msgid "Malformed LDAP URI!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:235
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:235
msgid "Please check that the URI starts with 'ldap://' or 'ldaps://'."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:243
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:243
msgid "The users base DN field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:250
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:250
msgid "Can't connect to LDAP server!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:250
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:312
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:250
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:312
msgid "Please check all the fields and your network connection."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:263
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:263
msgid "The Domain field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:277
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:277
msgid "Can't resolv the Active Directory Domain name!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:278
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:278
msgid "Please check the Domain field and your DNS configuration."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:286
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:286
msgid "The Workgroup field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:294
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:294
msgid "The AD administrator user field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:303
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:303
msgid "The AD administrator password field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/controller/UserAuthenticationMethodController.py:311
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:311
msgid "Can't connect to Active Directory server!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/GecosAccessDataDAO.py:178
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/WorkstationDataDAO.py:183
#: ../gecosws_config_assistant/dao/GecosAccessDataDAO.py:178
#: ../gecosws_config_assistant/dao/WorkstationDataDAO.py:183
msgid "Error removing file:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/LocalUserDAO.py:119
#: ../gecosws_config_assistant/dao/LocalUserDAO.py:119
msgid "Error creating user: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/LocalUserDAO.py:131
#: ../gecosws_config_assistant/dao/LocalUserDAO.py:131
msgid "Error modifying user name: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/LocalUserDAO.py:145
#: ../gecosws_config_assistant/dao/LocalUserDAO.py:145
msgid "Error modifying user password: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/LocalUserDAO.py:169
#: ../gecosws_config_assistant/dao/LocalUserDAO.py:169
msgid "Error deleting user: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/LocalUserDAO.py:179
#: ../gecosws_config_assistant/dao/LocalUserDAO.py:179
msgid "Error deleting user home: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/NTPServerDAO.py:68
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:79
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:131
#: ../gecosws_config_assistant/dao/NTPServerDAO.py:68
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:79
#: ../gecosws_config_assistant/util/PackageManager.py:131
msgid "Package installation failed:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/NTPServerDAO.py:95
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:523
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/WorkstationDataDAO.py:81
#: ../gecosws_config_assistant/dao/NTPServerDAO.py:95
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:523
#: ../gecosws_config_assistant/dao/WorkstationDataDAO.py:81
msgid "Error reading file:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/NTPServerDAO.py:99
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/NTPServerDAO.py:135
#: ../gecosws_config_assistant/dao/NTPServerDAO.py:99
#: ../gecosws_config_assistant/dao/NTPServerDAO.py:135
msgid "NTPServerDAO used without a proper initialization!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:175
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:201
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:249
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:360
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:387
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:413
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:448
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:484
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:175
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:201
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:249
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:360
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:387
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:413
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:448
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:484
msgid "Error running command: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:498
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:540
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:566
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:498
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:540
#: ../gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:566
msgid "UserAuthenticationMethodDAO used without a proper initialization!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/dao/WorkstationDataDAO.py:133
#: ../gecosws_config_assistant/dao/WorkstationDataDAO.py:133
msgid "Error writing file:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/JSONUtil.py:55
#: ../gecosws_config_assistant/util/JSONUtil.py:55
msgid "Error reading file: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:59
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:99
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:137
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:161
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:192
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:231
#: ../gecosws_config_assistant/util/PackageManager.py:59
#: ../gecosws_config_assistant/util/PackageManager.py:99
#: ../gecosws_config_assistant/util/PackageManager.py:137
#: ../gecosws_config_assistant/util/PackageManager.py:161
#: ../gecosws_config_assistant/util/PackageManager.py:192
#: ../gecosws_config_assistant/util/PackageManager.py:231
msgid "No apt library available"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:79
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:120
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:183
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:214
#: ../gecosws_config_assistant/util/PackageManager.py:79
#: ../gecosws_config_assistant/util/PackageManager.py:120
#: ../gecosws_config_assistant/util/PackageManager.py:183
#: ../gecosws_config_assistant/util/PackageManager.py:214
msgid "Package not found:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:81
#: ../gecosws_config_assistant/util/PackageManager.py:81
msgid "Package not installed:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:83
#: ../gecosws_config_assistant/util/PackageManager.py:83
msgid "Package not upgradable:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:93
#: ../gecosws_config_assistant/util/PackageManager.py:93
msgid "Package upgrade failed:"
msgstr ""

#. TODO: Yum version?
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:104
#: ../gecosws_config_assistant/util/PackageManager.py:104
msgid "Package upgrade failed!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:122
#: ../gecosws_config_assistant/util/PackageManager.py:122
msgid "Package already installed:"
msgstr ""

#. TODO: Yum version?
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:142
#: ../gecosws_config_assistant/util/PackageManager.py:142
msgid "Package installation failed!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:155
#: ../gecosws_config_assistant/util/PackageManager.py:155
msgid "Package update failed!"
msgstr ""

#. TODO: Yum version?
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:166
#: ../gecosws_config_assistant/util/PackageManager.py:166
msgid "Package cache update failed!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:185
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:216
#: ../gecosws_config_assistant/util/PackageManager.py:185
#: ../gecosws_config_assistant/util/PackageManager.py:216
msgid "Package is not installed:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:225
#: ../gecosws_config_assistant/util/PackageManager.py:225
msgid "Package removal failed:"
msgstr ""

#. TODO: Yum version?
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/PackageManager.py:236
#: ../gecosws_config_assistant/util/PackageManager.py:236
msgid "Package removal failed!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/util/Template.py:150
#: ../gecosws_config_assistant/util/Template.py:150
msgid "Error saving template:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:66
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:66
msgid "Active Directory credentials needed"
msgstr ""

#. Explanation
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:79
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:79
msgid "To setup or remove the Active Directory authentication method you"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:82
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:82
msgid "have to specify an AD administrator user and password:"
msgstr ""

#. Domain
#. text
#. Domain
#. text
#. Domain
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:87
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:137
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:244
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:140
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:87
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:137
#: ../gecosws_config_assistant/view/UserAuthDialog.py:244
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:140
msgid "Domain:"
msgstr ""

#. Workgroup
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:94
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:138
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:245
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:147
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:94
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:138
#: ../gecosws_config_assistant/view/UserAuthDialog.py:245
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:147
msgid "Workgroup:"
msgstr ""

#. User
#. Gecos CC user
#. User
#. Gecos CC user
#. User
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:101
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:132
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:246
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:154
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:101
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:132
#: ../gecosws_config_assistant/view/UserAuthDialog.py:246
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:154
msgid "User:"
msgstr ""

#. Password
#. Gecos CC password
#. Password
#. Gecos CC password
#. Password
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:111
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:142
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:98
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:247
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:163
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:111
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:142
#: ../gecosws_config_assistant/view/LocalUserElemView.py:98
#: ../gecosws_config_assistant/view/UserAuthDialog.py:247
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:163
msgid "Password:"
msgstr ""

#. Cancel button
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:122
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:91
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:116
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:122
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:91
#: ../gecosws_config_assistant/view/LocalUserElemView.py:116
msgid "Cancel"
msgstr ""

#. Accept button
#. Cancel button
#. Accept button
#. Cancel button
#. Accept button
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:127
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/AutoSetupProcessView.py:72
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:96
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:190
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:109
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:121
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:128
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:83
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:114
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:127
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:96
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:190
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:109
#: ../gecosws_config_assistant/view/LocalUserElemView.py:121
#: ../gecosws_config_assistant/view/LocalUserListView.py:128
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:83
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:114
msgid "Accept"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:164
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:164
msgid "Active Directory connection error"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ADSetupDataElemView.py:165
#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:165
msgid ""
"Can't connect to Active Directory.\n"
"Please double-check all the fields"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/AutoSetupProcessView.py:51
msgid "Auto setup process"
msgstr ""

#. Auto setup data load
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/AutoSetupProcessView.py:64
msgid "Loading setup data from GECOS Server"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:66
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:66
msgid "Url Chef Certificate Required"
msgstr ""

#. Explanation
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:79
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:79
msgid ""
"You need to enter url with certificate file\n"
" in protocol://domain/resource format"
msgstr ""

#. Certificate URL
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:83
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:83
msgid "Certificate URL:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:121
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:121
msgid "URL connection error"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ChefValidationCertificateDialog.py:122
#: ../gecosws_config_assistant/view/ChefValidationCertificateDialog.py:122
msgid "Can't get certificate file from this URL"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:76
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:76
msgid "Connect with GECOS Control Center"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:92
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:92
msgid "Workstation name"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:97
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:97
msgid "Workstation name must be unique. Spaces and symbols may be used."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:101
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:101
msgid "This description apperars in the GECOS control center reports."
msgstr ""

#. Workstation name field
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:105
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:105
msgid "Workstation name:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:118
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:118
msgid "GECOS Control Center Connection parameters"
msgstr ""

#. Gecos CC URL
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:122
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:122
msgid "GECOS Control Center URL:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:155
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:155
msgid "Select OU to connect to GECOS Control Center"
msgstr ""

#. Search filter
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:159
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:159
msgid "Search filter:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:167
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:167
msgid "Search"
msgstr ""

#. Select OU
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:172
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:172
msgid "Select OU:"
msgstr ""

#. Connect/disconnect to Gecos CC
#. elem
#. Connect/disconnect to Gecos CC
#. elem
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:185
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:228
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosDialog.py:158
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:185
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:228
#: ../gecosws_config_assistant/view/ConnectWithGecosDialog.py:158
msgid "Connect to GECOS CC"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:209
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/ConnectWithGecosDialog.py:142
#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:209
#: ../gecosws_config_assistant/view/ConnectWithGecosDialog.py:142
msgid "Disconnect from GECOS CC"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:51
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:51
msgid "GECOS CC connection process"
msgstr ""

#. Checking GECOS credentials
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:64
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:64
msgid "Check GECOS credentials"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:67
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:74
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:81
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:88
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:95
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:102
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:67
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:74
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:81
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:88
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:95
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:102
msgid "PENDING"
msgstr ""

#. Checking workstation data
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:71
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:71
msgid "Check workstation data"
msgstr ""

#. Obtaining Chef validation certificate
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:78
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:78
msgid "Get chef certificate"
msgstr ""

#. Registering computer in GECOS CC
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:92
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:92
msgid "Register in GECOS"
msgstr ""

#. Removing old configuration files
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/GecosCCSetupProcessView.py:99
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:99
msgid "Clean setup data"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:65
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:141
#: ../gecosws_config_assistant/view/LocalUserElemView.py:65
#: ../gecosws_config_assistant/view/LocalUserElemView.py:141
msgid "Add local user"
msgstr ""

#. Name
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:79
#: ../gecosws_config_assistant/view/LocalUserElemView.py:79
msgid "Name:"
msgstr ""

#. Login
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:88
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:121
#: ../gecosws_config_assistant/view/LocalUserElemView.py:88
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:121
msgid "Login:"
msgstr ""

#. Password confirmation
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:107
#: ../gecosws_config_assistant/view/LocalUserElemView.py:107
msgid "Confirm:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:133
#: ../gecosws_config_assistant/view/LocalUserElemView.py:133
msgid "Modifiy local user"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:155
#: ../gecosws_config_assistant/view/LocalUserElemView.py:155
msgid "The password confirmation field is empty!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserElemView.py:163
#: ../gecosws_config_assistant/view/LocalUserElemView.py:163
msgid "The password confirmation is different from password"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:62
#: ../gecosws_config_assistant/view/LocalUserListView.py:62
msgid "Manage local users"
msgstr ""

#. Explanation
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:75
#: ../gecosws_config_assistant/view/LocalUserListView.py:75
msgid "You can create, update or delete local users in this workstation."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:78
#: ../gecosws_config_assistant/view/LocalUserListView.py:78
msgid ""
"It isn't necessary to create here the users that are authenticated by "
"external services (LDAP, AD, ...)"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:84
#: ../gecosws_config_assistant/view/LocalUserListView.py:84
msgid "Please check default OEM users and change their passwords when needed:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:92
#: ../gecosws_config_assistant/view/LocalUserListView.py:92
msgid "Login"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:93
#: ../gecosws_config_assistant/view/LocalUserListView.py:93
msgid "Name"
msgstr ""

#. New user button
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:112
#: ../gecosws_config_assistant/view/LocalUserListView.py:112
msgid "New"
msgstr ""

#. Update user button
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:117
#: ../gecosws_config_assistant/view/LocalUserListView.py:117
msgid "Update"
msgstr ""

#. Delete user button
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/LocalUserListView.py:122
#: ../gecosws_config_assistant/view/LocalUserListView.py:122
msgid "Delete"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:51
msgid "GECOS config assistant"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:63
msgid "Check setup requirements"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:67
msgid "Connect / disconnect to GECOS Control Center"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:71
msgid "Setup user authentication method"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:75
msgid "Software manager"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:79
msgid "Local user manager"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:83
msgid "Update this assistant"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:88
msgid "View status"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:92
msgid "Close"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:106
msgid "Quit"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/MainMenuDialog_old.py:106
msgid "Do you want to quit?"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/NTPDialog.py:75
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/NTPServerElemView.py:109
#: ../gecosws_config_assistant/view/NTPServerElemView.py:109
msgid ""
"Can't connect with NTP server.\n"
"Please double-check the NTP server address"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/NTPDialog.py:78
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/NTPServerElemView.py:112
#: ../gecosws_config_assistant/view/NTPServerElemView.py:112
msgid "NTP server connection successful"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:65
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:65
msgid "System status"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:96
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:98
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:96
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:98
msgid "Assistant version: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:98
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:98
msgid "UNKNOWN VERSION"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:103
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:103
msgid "Workstation name: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:108
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:108
msgid "Time server: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:111
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:111
msgid "Network interfaces: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:117
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:117
msgid "GECOS Control Center connection data: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:120
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:120
msgid "Server URL:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:124
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:124
msgid "Local users: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:131
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:131
msgid "User authentication method: "
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:134
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:134
msgid "Method:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:141
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:141
msgid "Server URI:"
msgstr ""

#. Users base DN
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:142
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:213
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:219
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:142
#: ../gecosws_config_assistant/view/UserAuthDialog.py:213
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:219
msgid "Users base DN:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:143
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:143
msgid "Groups base DN:"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/SystemStatusElemView.py:148
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:148
msgid "No status data!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:209
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:207
#: ../gecosws_config_assistant/view/UserAuthDialog.py:209
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:207
msgid "Please fill the data to setup the LDAP authentication method."
msgstr ""

#. text
#. URI
#. text
#. URI
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:212
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:212
#: ../gecosws_config_assistant/view/UserAuthDialog.py:212
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:212
msgid "LDAP server URI:"
msgstr ""

#. Groups base DN
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:214
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:226
#: ../gecosws_config_assistant/view/UserAuthDialog.py:214
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:226
msgid "Groups base DN (optional):"
msgstr ""

#. Bind user DN
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:215
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:233
#: ../gecosws_config_assistant/view/UserAuthDialog.py:215
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:233
msgid "Bind user DN (optional):"
msgstr ""

#. Bind user password
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:216
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:241
#: ../gecosws_config_assistant/view/UserAuthDialog.py:216
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:241
msgid "Bind user password (optional):"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:241
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:136
#: ../gecosws_config_assistant/view/UserAuthDialog.py:241
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:136
msgid ""
"Please fill the data to setup the Active Directory authentication method."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:272
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:287
#: ../gecosws_config_assistant/view/UserAuthDialog.py:272
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:287
msgid ""
"There is no necessary data to setup the local users authentication method."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthDialog.py:364
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
#: ../gecosws_config_assistant/view/UserAuthDialog.py:364
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
msgid "An error happened while saving the users authentication method!"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:72
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:72
msgid "User authentication method"
msgstr ""

#. Explanation
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:85
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:85
msgid "The users of this workstation may authenticate by using"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:88
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:88
msgid "an external system like LDAP or Microsoft Active Directory."
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:91
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:91
msgid "Also, they can be authenticated by using local users of this O.S."
msgstr ""

#. Authentication Type
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:95
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:95
msgid "Authentication type:"
msgstr ""

#. Setup button
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:109
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:109
msgid "Setup"
msgstr ""

#. Options frame
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:125
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:125
msgid "Active Directory authentication"
msgstr ""

#. Options frame
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:196
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:196
msgid "LDAP authentication"
msgstr ""

#. Options frame
#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:276
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:276
msgid "Local users authentication"
msgstr ""

#: ../build/lib.linux-i686-2.7/gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:377
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:377
msgid "Error saving authentication method"
msgstr ""
